### ISSUE TITLE
say thanks and ask support

### ISSUE THREAD

**Issue by projectrifai** [sauanla/wedding-invitation#1]
hello sauanla, thank for your project,

i already try with your way, i tray to edit the content, can not. could you give the suggest?

**Comment by dinhphuc** [comment]
Hello @projectrifai,
Thanks for using it,
For edit content,

> In case HTML you can try select component in folder [View](https://github.com/sauanla/wedding-invitation/tree/main/views) and edit this.
> In case data render, you can try edit [seed-db](https://github.com/sauanla/wedding-invitation/blob/main/domains/mongodb/seed-db.js) and then run _http://localhost:3001/setup_ this is init data for first view

**Comment by projectrifai** [comment]
hello sauanla,
thanks for reply, i already try edit the contrnt, but i still not found to edit the married couple name.

**Comment by dinhphuc** [comment]
Hello @projectrifai
You should 
 - delete table **data_config** in mongo db first 
 - edit [seed-db](https://github.com/sauanla/wedding-invitation/blob/main/domains/mongodb/seed-db.js)
 - run http://localhost:3001/setup 
 
 Thanks.
